(add-to-list 'auto-mode-alist '("\\.js\\'" . js3-mode))
(add-to-list 'ac-modes 'js3-mode)
(custom-set-variables
 '(js3-auto-indent-p t)
 '(js3-indent-tabs-mode nil)
 '(js3-curly-indent-offset 0)
 '(js3-enter-indents-newline t)
 '(js3-expr-indent-offset 2)
 '(js3-indent-on-enter-key t)
 '(js3-paren-indent-offset 2)
 '(js3-square-indent-offset 2)
 '(js3-lazy-commas t)
 '(js3-lazy-dots t)
 '(js3-lazy-operators t)
 )
