(add-to-list 'auto-mode-alist '("\\.js\\'" . js3-mode))
(setq js3-indent-level 2)
(setq js3-indent-tabs-mode nil)
(setq js3-lazy-commas t)
(setq js3-lazy-operators t)
(setq js3-lazy-dots t)
(setq js3-expr-indent-offset 2)
(setq js3-paren-indent-offset 2)
(setq js3-square-indent-offset 2)
(setq js3-curly-indent-offset 2)
(setq js3-auto-indent-p t)
(setq js3-enter-indents-newline t)
(setq js3-indent-on-enter-key t)
;(add-hook 'js3-mode-hook
;          (lambda ()
;            (setq tab-width 2 indent-tabs-mode t)))
(add-to-list 'ac-modes 'js3-mode)
